### ISSUE TITLE
Weakening and onharm skills

### ISSUE THREAD

**Issue by RadoUzee** [naruto-unison/naruto-unison#31]
Expected: Shino uses bug on naruto to weaken him by 5. From then on every attack on naruto that trigers a shadow clone to pop should deal 5-5 = 0 damage to the attacker
Actual: The attacker still takes the 5 damage.

Not sure if this is intentional or a bug?

**Comment by jnbooth** [comment]
So this one is a little tricky. Naruto's shadow clones behave like traps, so I figured people would expect them to follow the rule that trap damage is not affected by weakening/strengthening. However, upon reflection, I'm not sure if there is a way to implement and describe him without confusing players. If a skill and its description do not make it immediately clear whether behaviors are intentional or bugs, I'd say they've failed to do their job. So it might be better to revert him to vanilla, which might be a good idea for the tutorial characters (i.e. Naruto, Sakura, and Sasuke) regardless. Thoughts?

**Comment by jnbooth** [comment]
Or are you saying that trap damage should be affected by weakening/strengthening?

**Comment by RadoUzee** [comment]
> Or are you saying that trap damage should be affected by weakening/strengthening?

Yes in my opinion it should be affected by weakening/strengthening . If i'm not mistaken in the original if Gai puts his counter and has a shino bug his damage deals 25 damage instead of 30.

and also about reverting Naruto to his original version, i think it's also the right choice. The current version might be confusing to newer players. I initially didn't understand it tbh i thought that he would deal 5x the number of clones he has left every time he gets attacked but it was actually 5 damage every time.
