### ISSUE TITLE
missions implementation :suggestion:

### ISSUE THREAD

**Issue by Kerodas** [naruto-unison/naruto-unison#33]
Hi, so I've got an idea about how to implement mission system. Since I don't know much about Haskell, I can't do that on my own.

Make new variables for characters code called unlocked, row, wins.

unlocked would have either true or false statement.
row and wins will be counted by victory screen.
If it appears during battle, add +1 to wins and +1 to row for characters used in the list.
If the lose screen appears, row changes back to 0.
If wins and row reaches same number that was written in characters code.
unlocked for that character will be true and character will be shown in the character list,
otherwise character will not be visible.

As for missions visibility, they will display values of wins and row from database.

It shouldn't be hard to make since those are basically if and for statements.

**Comment by jnbooth** [comment]
Well, I would like missions to be a bit more nuanced. In addition to straightforward win records, I think it would be neat to have 'grind' objectives such as "On <character>, successfully use <skill> 20 times" and 'challenge' ones such as "Complete a match with all team members at full health." Missions are in my opinion the backbone of the game, so I want them to be fun and varied. And I want there to be missions that people can work toward even if they are having a hard time getting victories due to being new, exhausted, unlucky with matchups, etc. Maybe even some PvE missions against specific AI teams.

Honestly, I think the system will be added as a skeleton but not fully developed until there is a public beta build and a Discord etc., so there can be lots of community feedback on what people would like/dislike in missions. Right now I don't have any idea what people would actually find fun or un-fun about those.

**Comment by jnbooth** [comment]
Well, I would like missions to be a bit more nuanced. In addition to straightforward win records, I think it would be neat to have 'grind' objectives such as "On \<character\>, successfully use \<skill\> 20 times" and 'challenge' ones such as "Complete a match with all team members at full health." Missions are in my opinion the backbone of the game, so I want them to be fun and varied. And I want there to be missions that people can work toward even if they are having a hard time getting victories due to being new, exhausted, unlucky with matchups, etc. Maybe even some PvE missions against specific AI teams.

Honestly, I think the system will be added as a skeleton but not fully developed until there is a public beta build and a Discord etc., so there can be lots of community feedback on what people would like/dislike in missions. Right now I don't have any idea what people would actually find fun or un-fun about those.

**Comment by Kerodas** [comment]
The same way can be organized PvE missions, but you will need to add IDs for each mission and add them to unlocked flag if completed.

Also I would suggest you to add skins system for character, like War of Ninja had, where players could use their own skins on already made characters. Like changing description, name of the characters and their icons, but at the same time those changes happen only on the account of a player who added them. People liked it.

**Comment by jnbooth** [comment]
Are you asking about the database representation? I think there would probably be two tables. One for pairs of user IDs and characters, so you could easily `unlockedChars <- unlockCharId <$> selectList [UnlockUserId ==. user] []` (or whatever), and then a bigger one for tracking progress on individual objectives. I suppose rows could be removed from the objectives table once the user unlocks the corresponding character, if size is a concern. I will have to look into whether there is a way in Yesod's persistent library to order by the quotient of two fields, so users could see their top 5 closest missions.

If you want to propose a skin system, you are certainly welcome to, but that should be a separate issue. That could even be handled entirely client-side by giving everything unique identifying classes, meaning skins could just be custom CSS themes. It's an interesting idea, regardless.

**Comment by Kerodas** [comment]
I suggest making a new db for missions where IDs of the users db.This way you can set flags for missions if completed or not.
As for skins, you can organize in the static folder with folders named after user IDs. This way users can change images.
As for names and a description, those can be assigned in a separated db.

**Comment by jnbooth** [comment]
If you read my above comment, I explain how the "db" tables are likely to be structured. The database is built on top of Yesod's [persistent](https://www.yesodweb.com/book/persistent) library; the "Relations" section of that link should help you understand how IDs are used in this framework. It would be a "many-to-many" relationship, like the "track which people have shopped in which stores" example in that link, but instead as "track which users have unlocked which characters." All of this is hypothetical, of course; missions will probably be the last thing added to the game, so that they can benefit from community feedback as they are being implemented.

If you read my above comment, you will also notice that I asked you to open a separate issue if you want to propose a skinning system.
