### ISSUE TITLE
Am i allowed to

### ISSUE THREAD

**Issue by RadoUzee** [naruto-unison/naruto-unison#4]
Am i allowed to use this and publish it on a site? As in removing all of your chars, then making my own and publish it? Most probably will be a non-profit project just for fun

**Comment by jnbooth** [comment]
N-U has a [BSD-3 License](https://github.com/naruto-unison/naruto-unison/blob/master/LICENSE), so you can do whatever you want with the code as long as you follow the terms of the license. I don't think it's anywhere close to being ready, but you're certainly welcome to give it a go. I would love to get a link to your site when you publish it! And if you implement a matchmaking system, which seems like it would be necessary in order to have an actual production server, feel free to open a pull request—I've been banging my head against that wall for a while.

**Comment by RadoUzee** [comment]
I was working with your brother on char creation but his lack of communication demotivated me and the fact that all of the chars he makes have huge walls of text(also he pretty much "fired" me after my 3rd to 5th char"). For now i simply want to put it online as to test simpler char designs with friends. Will try to add matchmaking much later as i actually don't know Haskel, Kien said you wanted to give me some books on it, but he hasn't sent them yet and it has been weeks so i found one myself: https://www.manning.com/books/exploring-haskell which I am starting to read now. But I also have some stuff to deal with in real life so might take some time before I make serious changes to the project itself. Currently have only played a bit with creating chars to understand how some mechanics are coded https://imgur.com/a/fq7HRBF

**Comment by jnbooth** [comment]
Hmm. The person I have doing most of my character designs is not my brother, nor would he have the ability to 'fire' someone, because right now this is just my personal hobby project, and even when this does become a public project I don't see any reason to give him much in the way of authority. Anyway, [Learn You a Haskell](http://learnyouahaskell.com/) is very good—it's how I got started with the language. Haskell is very cool!

**Comment by RadoUzee** [comment]
So you aren't Kienan's brother? Because he has a discord for naruto-unison and said his brother is doing the coding while he does the chars. And his brother is called Note.  https://discord.gg/PfjaY8
Plus he just posted a video of the newer version of n-u which with the select who you face.He said he will make a prealpha and give the link to 15 players. Said it a week ago, still hasn't sent them anything. He hired me to make some chars and paid me for 2 of them, but after that he said my other chars are lacking so he stopped the offer.

**Comment by jnbooth** [comment]
Uh

**Comment by jnbooth** [comment]
Okay. Kienan was the guy I formerly had doing my character designs, because I'm much better at the coding side than at game design. No family relation, no authority, certainly no capacity to launch a prealpha. The project isn't in a phase of adding new characters, so I'm not going to worry about finding a replacement for a while. I certainly don't see why that would be a paid position. This is an open-source project with no revenue.

For now, Naruto Unison is just me, and this repository is the full extent of its online presence. That's all it is right now: software in development. If at some point there does end up being a Discord server or an alpha release or something, the README will update to reflect that. It's open-source, so anyone could technically fork it and start promising prealphas and such, but I hope people will consider opening pull requests and joining the Naruto Unison team instead. This is slow going for one person to do on their own.

**Comment by RadoUzee** [comment]
Yeah It's just that he has been using you as an accessory and is still making others believe that you are working with him. Some even say that he has threatened them that Note will hack them if they don't do something. I got sent screenshots that inside some other discord he is now claiming that you have even found a 2nd coder and are going to release the project even faster.
I wouldn't mind working on that part for you for free( if you'd even want me :D). With Kienan the only reason i wanted pay was because he had it offered. But he made a lot of shady stuff, which i can't really type all of, because there's a lot. In short he was manipulative and toxic to his whole community and has destroyed the image of "naruto-unison" and i would honestly recommend using a different name for it. After I told you the truth he has been trying to twist it and paint me as trash inside of other discords...
On other news, i plan on trying to put my version on a free site today. I think i found your email on here so if you want the link I can send it there, since for now i don't want it to be too publicly visible.

**Comment by jnbooth** [comment]
I'm deleting that comment because it doesn't directly pertain to this repository. As far as the future of this project, to reiterate: anyone is welcome to open a pull request and start contributing, and I suspect that doing so will be far more productive than trying to split it off into a separate project, because—speaking from experience—this is very slow going for one person to do all on their own.
