### ISSUE TITLE
Registering an account

### ISSUE THREAD

**Issue by RadoUzee** [naruto-unison/naruto-unison#45]
I've always been using the dummy log in because registering an acc gives me the error:
INTERNAL SERVER ERROR
/usr/sbin/sendmail: createProcess: does not exist (No such file or directory)
but in dummy login you automatically have all charracters so i can't get the experience of how the exp/mission etc systems work. Is there a way to fix this error or is there a way to create a registered acc through the database? ( again sorry if the question is stupid)

**Comment by RadoUzee** [comment]
I thought i had found the answer but i guess i still don't fully understand databases. I tried ticking the verified field in user table. and setting a password from there. ( my ident being = email ) but when i tried it it didn't work. And sorry for posting multiple times, for some reason i can't seem to edit my posts

**Comment by jnbooth** [comment]
First of all, make sure that in [settings/config.yml](https://github.com/naruto-unison/naruto-unison/blob/master/config/settings.yml), you uncomment this line:
```yaml
#unlock-all: false
```
to
```yaml
unlock-all: false
```
Doing so overrides the default, which is to unlock all characters in `stack exec -- yesod devel` but not `stack exec -- yesod keter`. I think that will probably solve your problem.

So, about user creation. The database does not store your actual password, because that would be horrifyingly insecure. It stores a hash of it. Yesod's user registration system uses [sendmail](http://www.postfix.org/sendmail.1.html), a utility that is, unfortunately, only available on Linux. In lieu of sendmail, Yesod's [documentation](https://www.yesodweb.com/book/authentication-and-authorization#email) recommends creating an Amazon SES account and using the [mime-mail-ses](https://hackage.haskell.org/package/mime-mail-ses) package, but I have not personally looked into setting that up because it costs money—just $0.01 a month, mind you, but that obviously doesn't beat sendmail's $0.00.

However, you don't actually need any of this just for creating development users. As Yesod's aforementioned [documentation](https://www.yesodweb.com/book/authentication-and-authorization#email) describes, you can use the debugging console to access the authentication email link directly, without the need for an email client at all.

**Comment by jnbooth** [comment]
Did that resolve the issue for you?

**Comment by RadoUzee** [comment]
Sorry for the late reply, the "First of all, make sure that in settings/config.yml, you uncomment this line" fixed the problem with unlocked chars. I checked some out and i have feedback which i can post later.
As for the email thing, i haven't yet had the chance to test it on Linux.
