### ISSUE TITLE
Chakra question

### ISSUE THREAD

**Issue by Kerodas** [naruto-unison/naruto-unison#48]
How do you set color of chakra or add a new kind?

**Comment by jnbooth** [comment]
> How do you set color of chakra or add a new kind?

Chakra colors are classes in [templates/default-layout/default-layout.lucius](https://github.com/naruto-unison/naruto-unison/blob/master/templates/default-layout/default-layout.lucius).

> or add a new kind?

Like many open-source projects, Naruto Unison welcomes hacking on it, but will not provide support for doing so. If you want to write your own version of the game with more chakra types, blackjack, and professional escorts, that's great. If you want help with modifying the codebase, I think it will probably have to be for changes that you intend to open as pull requests and contribute to the project directly. That doesn't sound like your goal here.

As a starting point, I suggest looking in [Game.Model.Chakra](https://github.com/naruto-unison/naruto-unison/blob/master/src/Game/Model/Chakra.hs). The reason I point this module out is that it's explicitly imported at the top of every file that handles chakra (1 in 5 Haskell files, according to a quick CTRL+Shift+F), and explicitly qualified in function calls. The client-side Elm module is similarly named, and should be similarly easy to find. But since it wasn't, I think you probably don't know what you're doing, and will blow up the code if you try to make what you think are the appropriate changes. I wish you the best of luck,  but if that happens, I'm afraid you are on your own.

**Comment by Kerodas** [comment]
Don't get me wrong, I am just learning how things work, so I could bring up more things to the game and to open pull requests in the future. I was thinking about trying to implement 1 additional chakra slot that does not belong to others. Players could have only 1 per game and those could be used for ultimate skills of characters.

**Comment by jnbooth** [comment]
I've sometimes thought about connecting Overwatch-esque "ultimate abilities" to Sage chakra as a metaphor - something that accumulates over time, and exists outside of the boundaries of normal chakra. Never figured it out, though. Anyway, because of how different your idea is from ordinary chakra, you might find it easier to make it a completely different field (maybe in [Game.Model.Game](https://github.com/naruto-unison/naruto-unison/blob/master/src/Game/Model/Game.hs). That would also get around the risk of breaking something else.
