### ISSUE TITLE
Problems to fix

### ISSUE THREAD

**Issue by RadoUzee** [naruto-unison/naruto-unison#5]
Sasuke's sharingan text says 15 reduction, skill set to reduce flat 10 instead of 15
Kiba's Two-Headed Wolf doesn't work properly. Once stunned, his damage effect disappears completely, but his DR doesn't go away even if he's stunned.
Same for Lee's Action skill. Note: Lee's skill text says reduce by 10 but actually is written to reduce by 1
With the control channel, when gaara stuns someone, if he gets stunned on turn one, his skill will be canceled, but it will still be in its other form for the duration, not displaying the cooldown of the original skill.
There is no way to cancel a quick game search but for f5
f5 kills the whole game  If the timer runs out and a turn isn't played the game dies.  Wining in quick games doesn't result in a victory screen but instead in a frozen state

also it would be nice to add something that prevents you from clicking skills while they are stunned, because it can be confusing It returns the Chakra. Cooldown isn't activated, but it's confusing
same for when a target is invulnerable, being able to target them with non bypassing skills is confusing. It returns the Chakra but the cooldown is activated

PS: I don't understand why some skills have p Self $ vary "SKoriginal" "SKnew"  and others are vary' turns "SKoriginal" "SKnew"

**Comment by jnbooth** [comment]
Here, again, I think I should emphasize that **N-U is as much as a year away from alpha.** Nearly everything is unimplemented. Private matches don't even exist yet. This is far from a complete project. "WIP" would be a generous term.

Yes, clicking on skills under those conditions will soon be disabled. It was when the client was written in PureScript,  but it's one of the features I haven't fully plugged in since the move to Elm last month. Same goes for the victory screen. I'll see if I can replicate your issue of the game dying if a turn isn't played; the 60-second timer was only added last week, so it's certainly not yet stable.

The documentation is far from complete, and some of it is outdated, but in this case [it has your back](https://github.com/naruto-unison/naruto-unison/blob/master/src/Action/Skill.hs): 

> **vary:** Adds a `Variant` to `Ninja.variants` with a `Variant.dur` that depends on the `Skill.dur` of the `Skill` that performs the action. If the `Skill` is interrupted, the `Variant` immediately ends.

> **vary':** Adds a `Variant` to 'Ninja.variants' with a fixed `Variant.dur`.

`vary` is the function that should be used in most cases; it's the one for "While active, this skill becomes" etc. `vary'` is the function for effects like "During the next turn, this skill becomes" etc. It is also used for skills that are considered to last for as long as a Status they apply, even though their duration is Instant. If you search for the two functions, you'll see plenty of examples for both.

**Comment by RadoUzee** [comment]
Yes, I know it's far from ready, but as i am currently testing all of the chars that are already in the game, I wanted to share with you the bugs I find so that you can have them in mind for later and have an easier time releasing it bug-free.
And thanks for eplaining the vary/vary'
