### ISSUE TITLE
How exactly? ( the css part)

### ISSUE THREAD

**Issue by RadoUzee** [naruto-unison/naruto-unison#7]
How exactly can i change the css part of the project. Like if i want to change the title that appears (the html part) on top from naruto-unison to sth else, so i don't break the BSD lisence ?

**Comment by jnbooth** [comment]
If you want to fork this project into your own private instance instead of contributing to the repository, forgoing the benefits of collaboration in favor of delivering a half-baked, unfinished product that you yourself do not know how to improve, that's fine. It's your prerogative. But I'm not going to walk you through how to do it step by step.
