### ISSUE TITLE
Countering system

### ISSUE THREAD

**Issue by jnbooth** [naruto-unison/naruto-unison#8]
The current countering system is incomplete and unstable. It does not interact properly with skills that affect multiple targets and can cause unexpected chakra changes. There are several under-the-hood countering mechanisms, and their behavior is not entirely consistent.

**Comment by RadoUzee** [comment]
Just as an addition to the issues: When a skill that creates stacks is countered, it still generates a stack:

Expected: Guy puts counter on Gekko, GEkko uses move and is countered, since the skill didn't do anything, the stack doesn't generate
Actual: Gekko is countered, but he generates a stack that makes him deal 5 more damage

**Comment by jnbooth** [comment]
There is now an actual countering system, which should address the above concerns. It still needs work and testing, but at least it is stable, so I'm switching this to 'progress' for now.

**Comment by jnbooth** [comment]
Work and testing have been applied, and things seem to be going smoothly. I'm closing this, and if in the future any specific problems relating to counters occur, they are to be separate issues.
